// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * Mux is a simple HTTP route multiplexer that parses a request path,
 * records any URL params, and executes an end handler. It implements
 * the http.Handler interface and is friendly with the standard library.
 * 
 * Mux is designed to be fast, minimal and offer a powerful API for building
 * modular and composable HTTP services with a large set of handlers. It's
 * particularly useful for writing large REST API services that break a handler
 * into many smaller parts composed of middlewares and end handlers.
 */
export class Mux {
    /**
     * Creates a new Mux instance.
     * @param {Partial<Mux>} [$$source = {}] - The source object to create the Mux.
     */
    constructor($$source = {}) {

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Mux instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Mux}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Mux(/** @type {Partial<Mux>} */($$parsedSource));
    }
}
