package sandbox

import (
	"fmt"
	"os"
	"strings"
)

// Contributor defines a package that extends the JS sandbox environment
type Contributor interface {
	Name() string
	PolyfillSource() string         // JS code prepended to every execution
	TypesDefinition() string        // TS types combined into types.d.ts
}

// Global registry, automatically includes core contributor
var contributors = []Contributor{&coreContributor{}}

// Register adds a new sandbox contributor
func Register(c Contributor) {
	contributors = append(contributors, c)
}

// GenerateTypes combines all TypeScript definitions from contributors and writes them to the specified path
func GenerateTypes(outputPath string) error {
	var sb strings.Builder

	sb.WriteString("// Auto-generated by focusd\n\n")

	for _, c := range contributors {
		types := c.TypesDefinition()
		if types != "" {
			sb.WriteString(fmt.Sprintf("// --- Types for %s ---\n", c.Name()))
			sb.WriteString(types)
			sb.WriteString("\n\n")
		}
	}

	return os.WriteFile(outputPath, []byte(sb.String()), 0644)
}
