// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import type { Events } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import type * as timeline$0 from "../../../../focusd-so/focusd/internal/timeline/models.js";

declare module "@wailsio/runtime" {
    namespace Events {
        interface CustomEvents {
            "authctx:updated": any;
            "protection_status_changed": timeline$0.Event | null;
            "usage_changed": timeline$0.Event | null;
            "user_idle_changed": timeline$0.Event | null;
        }
    }
}
