//@ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as usage$0 from "../../../../focusd-so/focusd/internal/usage/models.js";

function configure() {
    Object.freeze(Object.assign($Create.Events, {
        "protection:status": $$createType0,
        "usage:update": $$createType1,
    }));
}

// Private type creation functions
const $$createType0 = usage$0.ProtectionPause.createFrom;
const $$createType1 = usage$0.ApplicationUsage.createFrom;

configure();
