//@ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as timeline$0 from "../../../../focusd-so/focusd/internal/timeline/models.js";

function configure() {
    Object.freeze(Object.assign($Create.Events, {
        "protection_status_changed": $$createType1,
        "usage_changed": $$createType1,
        "user_idle_changed": $$createType1,
    }));
}

// Private type creation functions
const $$createType0 = timeline$0.Event.createFrom;
const $$createType1 = $Create.Nullable($$createType0);

configure();
