//@ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as usage$0 from "../../../../focusd-so/focusd/internal/usage/models.js";

function configure() {
    Object.freeze(Object.assign($Create.Events, {
        "daily-summary:ready": $$createType0,
        "protection:status": $$createType1,
        "usage:update": $$createType3,
    }));
}

// Private type creation functions
const $$createType0 = usage$0.LLMDailySummary.createFrom;
const $$createType1 = usage$0.ProtectionPause.createFrom;
const $$createType2 = usage$0.ApplicationUsage.createFrom;
const $$createType3 = $Create.Nullable($$createType2);

configure();
