// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import type { Events } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import type * as updater$0 from "../../../../focusd-so/focusd/internal/updater/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import type * as usage$0 from "../../../../focusd-so/focusd/internal/usage/models.js";

declare module "@wailsio/runtime" {
    namespace Events {
        interface CustomEvents {
            "authctx:updated": any;
            "protection:status": usage$0.ProtectionPause;
            "update:available": updater$0.UpdateInfo | null;
            "usage:update": usage$0.ApplicationUsage;
        }
    }
}
