package usage

// LLMDailySummary is the persisted daily summary generated by the LLM.
type LLMDailySummary struct {
	ID         int64  `json:"id" gorm:"primaryKey;autoIncrement"`
	Date       string `json:"date" gorm:"uniqueIndex;not null"`
	Headline   string `json:"headline"`
	Narrative  string `json:"narrative"`
	KeyPattern string `json:"key_pattern"`
	Wins       string `json:"wins"` // JSON array of strings
	Suggestion string `json:"suggestion"`
	DayVibe    string `json:"day_vibe"`

	ContextSwitchCount  int `json:"context_switch_count"`
	LongestFocusMinutes int `json:"longest_focus_minutes"`
	DeepWorkMinutes     int `json:"deep_work_minutes"`
	BlockedAttemptCount int `json:"blocked_attempt_count"`

	CreatedAt int64 `json:"created_at"`
}

func (LLMDailySummary) TableName() string {
	return "llm_daily_summary"
}

// LLMDaySummaryInput is the pre-computed data that gets serialized and sent to the LLM.
// It is never stored -- only used as an intermediate representation.
type LLMDaySummaryInput struct {
	Date                   string                 `json:"date"`
	TotalProductiveMinutes int                    `json:"total_productive_minutes"`
	TotalDistractiveMinutes int                   `json:"total_distractive_minutes"`
	FocusScore             int                    `json:"focus_score"`
	ContextSwitchCount     int                    `json:"context_switch_count"`
	LongestFocusStretchMin int                    `json:"longest_focus_stretch_min"`
	DeepWorkSessions       []LLMDeepWorkSession   `json:"deep_work_sessions"`
	DeepWorkTotalMinutes   int                    `json:"deep_work_total_minutes"`
	DistractionCascades    []LLMDistractionCascade `json:"distraction_cascades"`
	TopDistractions        []LLMAppTimeSummary    `json:"top_distractions"`
	TopProductiveApps      []LLMAppTimeSummary    `json:"top_productive_apps"`
	MostProductiveHours    string                 `json:"most_productive_hours"`
	MostDistractiveHours   string                 `json:"most_distractive_hours"`
	BlockedAttemptCount    int                    `json:"blocked_attempt_count"`
	ProtectionPauseCount   int                    `json:"protection_pause_count"`
	AvgFocusScoreLast7Days int                    `json:"avg_focus_score_last_7_days"`
	FocusScoreTrend        string                 `json:"focus_score_trend"`
}

type LLMDeepWorkSession struct {
	Start   string `json:"start"`
	End     string `json:"end"`
	App     string `json:"app"`
	Minutes int    `json:"minutes"`
}

type LLMDistractionCascade struct {
	TriggerTime     string   `json:"trigger_time"`
	TriggerApp      string   `json:"trigger_app"`
	CascadeApps     []string `json:"cascade_apps"`
	TotalMinutes    int      `json:"total_minutes"`
	ReturnedToWork  string   `json:"returned_to_work_at"`
}

type LLMAppTimeSummary struct {
	App     string `json:"app"`
	Minutes int    `json:"minutes"`
	Visits  int    `json:"visits"`
}

// LLM response type for JSON parsing
type llmDailySummaryResponse struct {
	Headline   string   `json:"headline"`
	Narrative  string   `json:"narrative"`
	KeyPattern string   `json:"key_pattern"`
	Wins       []string `json:"wins"`
	Suggestion string   `json:"suggestion"`
	DayVibe    string   `json:"day_vibe"`
}
