package usage

import "time"

// LLMDailySummary is the persisted daily summary generated by the LLM.
type LLMDailySummary struct {
	ID         int64  `json:"id" gorm:"primaryKey;autoIncrement"`
	Date       string `json:"date" gorm:"uniqueIndex;not null"`
	Headline   string `json:"headline"`
	Narrative  string `json:"narrative"`
	KeyPattern string `json:"key_pattern"`
	Wins       string `json:"wins"` // JSON array of strings
	Suggestion string `json:"suggestion"`
	DayVibe    string `json:"day_vibe"`

	ContextSwitchCount  int `json:"context_switch_count"`
	LongestFocusMinutes int `json:"longest_focus_minutes"`
	DeepWorkMinutes     int `json:"deep_work_minutes"`
	BlockedAttemptCount int `json:"blocked_attempt_count"`

	CreatedAt int64 `json:"created_at"`
}

func (LLMDailySummary) TableName() string {
	return "llm_daily_summary"
}

// LLMDaySummaryInput is the pre-computed data that gets serialized and sent to the LLM.
// It is never stored -- only used as an intermediate representation.
type LLMDaySummaryInput struct {
	Date                   string                 `json:"date"`
	TotalProductiveMinutes int                    `json:"total_productive_minutes"`
	TotalDistractiveMinutes int                   `json:"total_distractive_minutes"`
	FocusScore             int                    `json:"focus_score"`
	ContextSwitchCount     int                    `json:"context_switch_count"`
	LongestFocusStretchMin int                    `json:"longest_focus_stretch_min"`
	DeepWorkSessions       []LLMDeepWorkSession   `json:"deep_work_sessions"`
	DeepWorkTotalMinutes   int                    `json:"deep_work_total_minutes"`
	DistractionCascades    []LLMDistractionCascade `json:"distraction_cascades"`
	TopDistractions        []LLMAppTimeSummary    `json:"top_distractions"`
	TopProductiveApps      []LLMAppTimeSummary    `json:"top_productive_apps"`
	MostProductiveHours    string                 `json:"most_productive_hours"`
	MostDistractiveHours   string                 `json:"most_distractive_hours"`
	BlockedAttemptCount    int                    `json:"blocked_attempt_count"`
	ProtectionPauseCount   int                    `json:"protection_pause_count"`
	AvgFocusScoreLast7Days int                    `json:"avg_focus_score_last_7_days"`
	FocusScoreTrend        string                 `json:"focus_score_trend"`
}

func (i LLMDaySummaryInput) hasMinimumData() bool {
	totalTrackedSecs := (i.TotalProductiveMinutes + i.TotalDistractiveMinutes) * 60
	return totalTrackedSecs >= minSecondsForSummary
}

type LLMDeepWorkSession struct {
	Start   string `json:"start"`
	End     string `json:"end"`
	App     string `json:"app"`
	Minutes int    `json:"minutes"`
}

type LLMDistractionCascade struct {
	TriggerTime     string   `json:"trigger_time"`
	TriggerApp      string   `json:"trigger_app"`
	CascadeApps     []string `json:"cascade_apps"`
	TotalMinutes    int      `json:"total_minutes"`
	ReturnedToWork  string   `json:"returned_to_work_at"`
}

type LLMAppTimeSummary struct {
	App     string `json:"app"`
	Minutes int    `json:"minutes"`
	Visits  int    `json:"visits"`
}

// LLM response type for JSON parsing
type llmDailySummaryResponse struct {
	Headline   string   `json:"headline"`
	Narrative  string   `json:"narrative"`
	KeyPattern string   `json:"key_pattern"`
	Wins       []string `json:"wins"`
	Suggestion string   `json:"suggestion"`
	DayVibe    string   `json:"day_vibe"`
}

// deepWorkTracker tracks consecutive productive blocks and emits sessions >= 25min.
type deepWorkTracker struct {
	currentStart int64
	currentSecs  int
	currentApp   string
	sessions     []LLMDeepWorkSession
}

func (t *deepWorkTracker) processProductive(startedAt int64, dur int, appName string) {
	if t.currentStart == 0 {
		t.currentStart = startedAt
		t.currentApp = appName
	}
	t.currentSecs += dur
}

func (t *deepWorkTracker) processDistracting(startedAt int64) {
	if t.currentSecs >= deepWorkThresholdSecs {
		t.sessions = append(t.sessions, LLMDeepWorkSession{
			Start:   time.Unix(t.currentStart, 0).Format("3:04pm"),
			End:     time.Unix(startedAt, 0).Format("3:04pm"),
			App:     t.currentApp,
			Minutes: t.currentSecs / 60,
		})
	}
	t.currentStart = 0
	t.currentSecs = 0
	t.currentApp = ""
}

func (t *deepWorkTracker) flush(lastEnd time.Time) {
	if t.currentSecs >= deepWorkThresholdSecs {
		t.sessions = append(t.sessions, LLMDeepWorkSession{
			Start:   time.Unix(t.currentStart, 0).Format("3:04pm"),
			End:     lastEnd.Format("3:04pm"),
			App:     t.currentApp,
			Minutes: t.currentSecs / 60,
		})
	}
}

func (t *deepWorkTracker) totalMinutes() int {
	total := 0
	for _, s := range t.sessions {
		total += s.Minutes
	}
	return total
}

// focusStretchTracker tracks the longest uninterrupted productive run.
type focusStretchTracker struct {
	currentSecs int
	longestSecs int
}

func (t *focusStretchTracker) addProductive(dur int) {
	t.currentSecs += dur
	if t.currentSecs > t.longestSecs {
		t.longestSecs = t.currentSecs
	}
}

func (t *focusStretchTracker) reset() {
	t.currentSecs = 0
}

func (t *focusStretchTracker) longestMinutes() int {
	return t.longestSecs / 60
}

// cascadeTracker tracks sequences of consecutive distracting apps.
type cascadeTracker struct {
	start    int64
	apps     []string
	secs     int
	trigger  string
	cascades []LLMDistractionCascade
}

func (t *cascadeTracker) addDistracting(startedAt int64, dur int, appName string) {
	if len(t.apps) == 0 {
		t.start = startedAt
		t.trigger = appName
	}
	t.apps = append(t.apps, appName)
	t.secs += dur
}

func (t *cascadeTracker) endCascade(returnedAt int64) {
	if len(t.apps) == 0 {
		return
	}
	t.cascades = append(t.cascades, LLMDistractionCascade{
		TriggerTime:    time.Unix(t.start, 0).Format("3:04pm"),
		TriggerApp:     t.trigger,
		CascadeApps:    uniqueStrings(t.apps),
		TotalMinutes:   t.secs / 60,
		ReturnedToWork: time.Unix(returnedAt, 0).Format("3:04pm"),
	})
	t.apps = nil
	t.secs = 0
}

func (t *cascadeTracker) flush() {
	if len(t.apps) > 1 {
		t.cascades = append(t.cascades, LLMDistractionCascade{
			TriggerTime:  time.Unix(t.start, 0).Format("3:04pm"),
			TriggerApp:   t.trigger,
			CascadeApps:  uniqueStrings(t.apps),
			TotalMinutes: t.secs / 60,
		})
	}
}
