// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as time$0 from "../../../../../time/models.js";

export class Application {
    /**
     * Creates a new Application instance.
     * @param {Partial<Application>} [$$source = {}] - The source object to create the Application.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["id"] = 0;
        }
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("executable_path" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["executable_path"] = "";
        }
        if (!("icon" in $$source)) {
            /**
             * either app icon or favicon
             * @member
             * @type {string}
             */
            this["icon"] = "";
        }
        if (!("hostname" in $$source)) {
            /**
             * @member
             * @type {string | null}
             */
            this["hostname"] = null;
        }
        if (!("domain" in $$source)) {
            /**
             * @member
             * @type {string | null}
             */
            this["domain"] = null;
        }
        if (!("bundle_id" in $$source)) {
            /**
             * darwin only
             * @member
             * @type {string | null}
             */
            this["bundle_id"] = null;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Application instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Application}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Application(/** @type {Partial<Application>} */($$parsedSource));
    }
}

export class ApplicationUsage {
    /**
     * Creates a new ApplicationUsage instance.
     * @param {Partial<ApplicationUsage>} [$$source = {}] - The source object to create the ApplicationUsage.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["id"] = 0;
        }
        if (!("window_title" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["window_title"] = "";
        }
        if (!("browser_url" in $$source)) {
            /**
             * @member
             * @type {string | null}
             */
            this["browser_url"] = null;
        }
        if (!("started_at" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["started_at"] = 0;
        }
        if (!("ended_at" in $$source)) {
            /**
             * @member
             * @type {number | null}
             */
            this["ended_at"] = null;
        }
        if (!("duration_seconds" in $$source)) {
            /**
             * @member
             * @type {number | null}
             */
            this["duration_seconds"] = null;
        }
        if (!("classification" in $$source)) {
            /**
             * @member
             * @type {Classification}
             */
            this["classification"] = Classification.$zero;
        }
        if (!("classification_reasoning" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["classification_reasoning"] = "";
        }
        if (!("classification_error" in $$source)) {
            /**
             * @member
             * @type {string | null}
             */
            this["classification_error"] = null;
        }
        if (!("classification_confidence" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["classification_confidence"] = 0;
        }
        if (!("classification_source" in $$source)) {
            /**
             * @member
             * @type {ClassificationSource}
             */
            this["classification_source"] = ClassificationSource.$zero;
        }
        if (!("detected_project" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["detected_project"] = "";
        }
        if (!("detected_communication_channel" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["detected_communication_channel"] = "";
        }
        if (!("termination_mode" in $$source)) {
            /**
             * @member
             * @type {TerminationMode}
             */
            this["termination_mode"] = TerminationMode.$zero;
        }
        if (!("termination_reasoning" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["termination_reasoning"] = "";
        }
        if (!("termination_mode_source" in $$source)) {
            /**
             * @member
             * @type {TerminationModeSource}
             */
            this["termination_mode_source"] = TerminationModeSource.$zero;
        }
        if (!("termination_mode_error" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["termination_mode_error"] = "";
        }
        if (!("tags" in $$source)) {
            /**
             * relations
             * @member
             * @type {ApplicationUsageTags[]}
             */
            this["tags"] = [];
        }
        if (!("application_id" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["application_id"] = 0;
        }
        if (!("application" in $$source)) {
            /**
             * @member
             * @type {Application}
             */
            this["application"] = (new Application());
        }
        if (!("execution_log_id" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["execution_log_id"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ApplicationUsage instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ApplicationUsage}
     */
    static createFrom($$source = {}) {
        const $$createField17_0 = $$createType1;
        const $$createField19_0 = $$createType2;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("tags" in $$parsedSource) {
            $$parsedSource["tags"] = $$createField17_0($$parsedSource["tags"]);
        }
        if ("application" in $$parsedSource) {
            $$parsedSource["application"] = $$createField19_0($$parsedSource["application"]);
        }
        return new ApplicationUsage(/** @type {Partial<ApplicationUsage>} */($$parsedSource));
    }
}

export class ApplicationUsageTags {
    /**
     * Creates a new ApplicationUsageTags instance.
     * @param {Partial<ApplicationUsageTags>} [$$source = {}] - The source object to create the ApplicationUsageTags.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["id"] = 0;
        }
        if (!("tag" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["tag"] = "";
        }
        if (!("usage_id" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["usage_id"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ApplicationUsageTags instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ApplicationUsageTags}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ApplicationUsageTags(/** @type {Partial<ApplicationUsageTags>} */($$parsedSource));
    }
}

/**
 * @readonly
 * @enum {string}
 */
export const Classification = {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero: "",

    ClassificationError: "unknown",
    ClassificationProductive: "productive",
    ClassificationDistracting: "distracting",
    ClassificationNeutral: "neutral",
    ClassificationSystem: "system",
};

export class ClassificationResponse {
    /**
     * Creates a new ClassificationResponse instance.
     * @param {Partial<ClassificationResponse>} [$$source = {}] - The source object to create the ClassificationResponse.
     */
    constructor($$source = {}) {
        if (!("classification" in $$source)) {
            /**
             * @member
             * @type {Classification}
             */
            this["classification"] = Classification.$zero;
        }
        if (!("classification_source" in $$source)) {
            /**
             * @member
             * @type {ClassificationSource}
             */
            this["classification_source"] = ClassificationSource.$zero;
        }
        if (!("reasoning" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["reasoning"] = "";
        }
        if (!("confidence_score" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["confidence_score"] = 0;
        }
        if (!("detected_project" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["detected_project"] = "";
        }
        if (!("detected_communication_channel" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["detected_communication_channel"] = "";
        }
        if (!("tags" in $$source)) {
            /**
             * @member
             * @type {string[]}
             */
            this["tags"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ClassificationResponse instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ClassificationResponse}
     */
    static createFrom($$source = {}) {
        const $$createField6_0 = $$createType3;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("tags" in $$parsedSource) {
            $$parsedSource["tags"] = $$createField6_0($$parsedSource["tags"]);
        }
        return new ClassificationResponse(/** @type {Partial<ClassificationResponse>} */($$parsedSource));
    }
}

/**
 * @readonly
 * @enum {string}
 */
export const ClassificationSource = {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero: "",

    ClassificationSourceUserSet: "user_set",
    ClassificationSourceObviously: "obviously",
    ClassificationSourceCloudLLM: "llm",
    ClassificationSourceCustomRules: "custom_rules",
};

export class DayInsights {
    /**
     * Creates a new DayInsights instance.
     * @param {Partial<DayInsights>} [$$source = {}] - The source object to create the DayInsights.
     */
    constructor($$source = {}) {
        if (!("ProductivityScore" in $$source)) {
            /**
             * @member
             * @type {ProductivityScore}
             */
            this["ProductivityScore"] = (new ProductivityScore());
        }
        if (!("ProductivityPerHourBreakdown" in $$source)) {
            /**
             * @member
             * @type {ProductivityPerHourBreakdown}
             */
            this["ProductivityPerHourBreakdown"] = {};
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DayInsights instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {DayInsights}
     */
    static createFrom($$source = {}) {
        const $$createField0_0 = $$createType4;
        const $$createField1_0 = $$createType5;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("ProductivityScore" in $$parsedSource) {
            $$parsedSource["ProductivityScore"] = $$createField0_0($$parsedSource["ProductivityScore"]);
        }
        if ("ProductivityPerHourBreakdown" in $$parsedSource) {
            $$parsedSource["ProductivityPerHourBreakdown"] = $$createField1_0($$parsedSource["ProductivityPerHourBreakdown"]);
        }
        return new DayInsights(/** @type {Partial<DayInsights>} */($$parsedSource));
    }
}

export class GetUsageListOptions {
    /**
     * Creates a new GetUsageListOptions instance.
     * @param {Partial<GetUsageListOptions>} [$$source = {}] - The source object to create the GetUsageListOptions.
     */
    constructor($$source = {}) {
        if (!("Date" in $$source)) {
            /**
             * @member
             * @type {time$0.Time | null}
             */
            this["Date"] = null;
        }
        if (!("Page" in $$source)) {
            /**
             * @member
             * @type {number | null}
             */
            this["Page"] = null;
        }
        if (!("PageSize" in $$source)) {
            /**
             * @member
             * @type {number | null}
             */
            this["PageSize"] = null;
        }
        if (!("StartedAt" in $$source)) {
            /**
             * @member
             * @type {time$0.Time | null}
             */
            this["StartedAt"] = null;
        }
        if (!("EndedAt" in $$source)) {
            /**
             * @member
             * @type {time$0.Time | null}
             */
            this["EndedAt"] = null;
        }
        if (!("TerminationMode" in $$source)) {
            /**
             * @member
             * @type {TerminationMode | null}
             */
            this["TerminationMode"] = null;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new GetUsageListOptions instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {GetUsageListOptions}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new GetUsageListOptions(/** @type {Partial<GetUsageListOptions>} */($$parsedSource));
    }
}

/**
 * @typedef {{ [_: string]: ProductivityScore }} ProductivityPerHourBreakdown
 */

export class ProductivityScore {
    /**
     * Creates a new ProductivityScore instance.
     * @param {Partial<ProductivityScore>} [$$source = {}] - The source object to create the ProductivityScore.
     */
    constructor($$source = {}) {
        if (!("ProductiveSeconds" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["ProductiveSeconds"] = 0;
        }
        if (!("DistractiveSeconds" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["DistractiveSeconds"] = 0;
        }
        if (!("OtherSeconds" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["OtherSeconds"] = 0;
        }
        if (!("ProductivityScore" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["ProductivityScore"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ProductivityScore instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ProductivityScore}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ProductivityScore(/** @type {Partial<ProductivityScore>} */($$parsedSource));
    }
}

export class ProtectionPause {
    /**
     * Creates a new ProtectionPause instance.
     * @param {Partial<ProtectionPause>} [$$source = {}] - The source object to create the ProtectionPause.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["id"] = 0;
        }
        if (!("requested_duration_seconds" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["requested_duration_seconds"] = 0;
        }
        if (!("actual_duration_seconds" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["actual_duration_seconds"] = 0;
        }
        if (!("resumed_at" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["resumed_at"] = 0;
        }
        if (!("resumed_reason" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["resumed_reason"] = "";
        }
        if (!("created_at" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["created_at"] = 0;
        }
        if (!("reason" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["reason"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ProtectionPause instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ProtectionPause}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ProtectionPause(/** @type {Partial<ProtectionPause>} */($$parsedSource));
    }
}

export class ProtectionWhitelist {
    /**
     * Creates a new ProtectionWhitelist instance.
     * @param {Partial<ProtectionWhitelist>} [$$source = {}] - The source object to create the ProtectionWhitelist.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["id"] = 0;
        }
        if (!("executable_path" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["executable_path"] = "";
        }
        if (!("hostname" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["hostname"] = "";
        }
        if (!("url" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["url"] = "";
        }
        if (!("expires_at" in $$source)) {
            /**
             * nil = allow indefinitely, otherwise Unix timestamp
             * @member
             * @type {number}
             */
            this["expires_at"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ProtectionWhitelist instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ProtectionWhitelist}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ProtectionWhitelist(/** @type {Partial<ProtectionWhitelist>} */($$parsedSource));
    }
}

export class SandboxExecutionLog {
    /**
     * Creates a new SandboxExecutionLog instance.
     * @param {Partial<SandboxExecutionLog>} [$$source = {}] - The source object to create the SandboxExecutionLog.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["id"] = 0;
        }
        if (!("context" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["context"] = "";
        }
        if (!("response" in $$source)) {
            /**
             * @member
             * @type {string | null}
             */
            this["response"] = null;
        }
        if (!("logs" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["logs"] = "";
        }
        if (!("created_at" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["created_at"] = 0;
        }
        if (!("finished_at" in $$source)) {
            /**
             * @member
             * @type {number | null}
             */
            this["finished_at"] = null;
        }
        if (!("error" in $$source)) {
            /**
             * @member
             * @type {string | null}
             */
            this["error"] = null;
        }
        if (!("type" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["type"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SandboxExecutionLog instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {SandboxExecutionLog}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SandboxExecutionLog(/** @type {Partial<SandboxExecutionLog>} */($$parsedSource));
    }
}

export class TerminationDecision {
    /**
     * Creates a new TerminationDecision instance.
     * @param {Partial<TerminationDecision>} [$$source = {}] - The source object to create the TerminationDecision.
     */
    constructor($$source = {}) {
        if (!("Mode" in $$source)) {
            /**
             * @member
             * @type {TerminationMode}
             */
            this["Mode"] = TerminationMode.$zero;
        }
        if (!("Reasoning" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["Reasoning"] = "";
        }
        if (!("Source" in $$source)) {
            /**
             * @member
             * @type {TerminationModeSource}
             */
            this["Source"] = TerminationModeSource.$zero;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new TerminationDecision instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {TerminationDecision}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new TerminationDecision(/** @type {Partial<TerminationDecision>} */($$parsedSource));
    }
}

/**
 * @readonly
 * @enum {string}
 */
export const TerminationMode = {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero: "",

    TerminationModeNone: "none",
    TerminationModeBlock: "block",
    TerminationModePaused: "paused",
    TerminationModeAllow: "allow",
};

/**
 * @readonly
 * @enum {string}
 */
export const TerminationModeSource = {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero: "",

    TerminationModeSourceApplication: "application",
    TerminationModeSourceCustomRules: "custom_rules",
    TerminationModeSourceWhitelist: "whitelist",
    TerminationModeSourcePaused: "paused",
};

/**
 * sandboxContext provides context for the current rule execution including usage data and helper functions
 */
export class sandboxContext {
    /**
     * Creates a new sandboxContext instance.
     * @param {Partial<sandboxContext>} [$$source = {}] - The source object to create the sandboxContext.
     */
    constructor($$source = {}) {
        if (!("appName" in $$source)) {
            /**
             * Input data
             * @member
             * @type {string}
             */
            this["appName"] = "";
        }
        if (!("executablePath" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["executablePath"] = "";
        }
        if (!("hostname" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["hostname"] = "";
        }
        if (!("path" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["path"] = "";
        }
        if (!("domain" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["domain"] = "";
        }
        if (!("url" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["url"] = "";
        }
        if (!("classification" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["classification"] = "";
        }
        if (!("minutesSinceLastBlock" in $$source)) {
            /**
             * Helper pre-computed values
             * @member
             * @type {number | null}
             */
            this["minutesSinceLastBlock"] = null;
        }
        if (!("minutesUsedSinceLastBlock" in $$source)) {
            /**
             * @member
             * @type {number | null}
             */
            this["minutesUsedSinceLastBlock"] = null;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new sandboxContext instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {sandboxContext}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new sandboxContext(/** @type {Partial<sandboxContext>} */($$parsedSource));
    }
}

// Private type creation functions
const $$createType0 = ApplicationUsageTags.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = Application.createFrom;
const $$createType3 = $Create.Array($Create.Any);
const $$createType4 = ProductivityScore.createFrom;
var $$createType5 = /** @type {(...args: any[]) => any} */(function $$initCreateType5(...args) {
    if ($$createType5 === $$initCreateType5) {
        $$createType5 = $$createType6;
    }
    return $$createType5(...args);
});
const $$createType6 = $Create.Map($Create.Any, $$createType4);
