// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as chi$0 from "../../../../go-chi/chi/v5/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as time$0 from "../../../../../time/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * CalculateTerminationMode determines whether an application or website should be blocked, allowed, or paused based on classification, custom rules, protection status, and whitelist entries.
 * 
 * This function evaluates multiple factors in order of priority:
 * 1. Custom rules (if configured) - highest priority
 * 2. Classification - non-distracting usage is always allowed
 * 3. Protection pause status - if protection is paused, usage is allowed
 * 4. Whitelist entries - temporarily whitelisted bundle ID/hostname combinations are allowed
 * 5. Default blocking - distracting usage is blocked when protection is active
 * 
 * Parameters:
 *   - bundleID: The application bundle identifier (e.g., "com.example.app")
 *   - hostname: The website hostname (e.g., "example.com") - empty string for non-browser apps
 *   - domain: The domain name extracted from the URL
 *   - url: The full URL being accessed
 *   - classification: The classification result indicating whether the usage is distracting
 *   - terminationMode: The requested termination mode (may be overridden by custom rules)
 * 
 * Returns:
 *   - TerminationDecision: A decision containing the mode (Allow/Block/Paused), reasoning, and source
 *   - error: Database error if protection status or whitelist lookup fails
 * @param {$models.ApplicationUsage | null} appUsage
 * @returns {$CancellablePromise<$models.TerminationDecision>}
 */
export function CalculateTerminationMode(appUsage) {
    return $Call.ByID(117623320, appUsage).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * @param {string} appName
 * @param {string} executablePath
 * @param {string | null} url
 * @returns {$CancellablePromise<$models.ClassificationResponse | null>}
 */
export function ClassifyCustomRules(appName, executablePath, url) {
    return $Call.ByID(1276707747, appName, executablePath, url).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType2($result);
    }));
}

/**
 * @param {$models.sandboxContext} sandboxCtx
 * @returns {$CancellablePromise<$models.ClassificationResponse | null>}
 */
export function ClassifyCustomRulesWithSandbox(sandboxCtx) {
    return $Call.ByID(434071758, sandboxCtx).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType2($result);
    }));
}

/**
 * @param {string} appName
 * @param {string} title
 * @param {string} executablePath
 * @param {string | null} url
 * @returns {$CancellablePromise<$models.ClassificationResponse | null>}
 */
export function ClassifyWithLLM(appName, title, executablePath, url) {
    return $Call.ByID(3036897070, appName, title, executablePath, url).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType2($result);
    }));
}

/**
 * @param {time$0.Time} date
 * @returns {$CancellablePromise<$models.DayInsights>}
 */
export function GetDayInsights(date) {
    return $Call.ByID(101857534, date).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType3($result);
    }));
}

/**
 * GetPauseHistory retrieves the history of protection pauses within the specified number of days.
 * 
 * Parameters:
 *   - days: The number of days to look back (e.g., 7 for one week)
 * 
 * Returns:
 *   - []ProtectionPause: A slice of pause records ordered by creation time (newest first)
 *   - error: Database error if the query fails
 * @param {number} days
 * @returns {$CancellablePromise<$models.ProtectionPause[]>}
 */
export function GetPauseHistory(days) {
    return $Call.ByID(3211421177, days).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType5($result);
    }));
}

/**
 * GetProtectionStatus retrieves the current protection pause status.
 * 
 * It queries for an active ProtectionPause record where ResumedAt is greater than
 * the current time (indicating the pause is still active and hasn't been resumed yet).
 * When a pause is created, ResumedAt is set to a future timestamp representing when
 * the pause should automatically expire. When manually resumed, ResumedAt is updated
 * to the current time, making it no longer match this query.
 * 
 * Returns:
 *   - ProtectionPause: The active pause record if protection is currently paused,
 *     or an empty ProtectionPause (ID == 0) if protection is active (not paused)
 *   - error: Database error if the query fails
 * @returns {$CancellablePromise<$models.ProtectionPause>}
 */
export function GetProtectionStatus() {
    return $Call.ByID(1205560554).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType4($result);
    }));
}

/**
 * GetSandboxExecutionLogs retrieves paginated sandbox execution logs from the database.
 * It supports fuzzy search on context and response fields, and filtering by log type.
 * Only returns logs from the last 7 days.
 * @param {string} logType
 * @param {string} search
 * @param {number} page
 * @param {number} pageSize
 * @returns {$CancellablePromise<$models.SandboxExecutionLog[]>}
 */
export function GetSandboxExecutionLogs(logType, search, page, pageSize) {
    return $Call.ByID(2542111835, logType, search, page, pageSize).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType7($result);
    }));
}

/**
 * GetUsageList returns a list of application usages for the given date and pagination options
 * 
 * Parameters:
 *   - options: GetUsageListOptions
 *   - Date: The date to get usages for - useful for detailed analysis of a specific day usage
 *   - Page: The page number to get
 *   - PageSize: The number of usages per page
 * 
 * Returns:
 *   - []ApplicationUsage: The list of application usages
 * @param {$models.GetUsageListOptions} options
 * @returns {$CancellablePromise<$models.ApplicationUsage[]>}
 */
export function GetUsageList(options) {
    return $Call.ByID(3310698242, options).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType9($result);
    }));
}

/**
 * GetWhitelist returns all active whitelist entries that haven't expired.
 * 
 * Returns:
 *   - []ProtectionWhitelist: A slice of active whitelist entries
 *   - error: Database error if the query fails
 * @returns {$CancellablePromise<$models.ProtectionWhitelist[]>}
 */
export function GetWhitelist() {
    return $Call.ByID(1370636440).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType11($result);
    }));
}

/**
 * IdleChanged is called when the idle state of the user changes (e.g. user starts or stops using the computer)
 * @param {boolean} isIdle
 * @returns {$CancellablePromise<void>}
 */
export function IdleChanged(isIdle) {
    return $Call.ByID(3172421449, isIdle);
}

/**
 * PauseProtection temporarily disables focus protection for the specified duration.
 * 
 * The function starts a background goroutine that automatically resumes protection
 * after the duration expires. The pause state is persisted to the database, allowing
 * the application to recover pause state across restarts.
 * 
 * Parameters:
 *   - duration: The duration to pause protection (must be > 0)
 * 
 * Returns:
 *   - error: Returns an error if protection is already paused
 * 
 * Side effects:
 *   - Creates a ProtectionPause record in the database
 *   - Emits a state update via the state channel
 *   - Spawns a goroutine that calls ResumeProtection after the duration
 * @param {number} durationSeconds
 * @param {string} reason
 * @returns {$CancellablePromise<$models.ProtectionPause>}
 */
export function PauseProtection(durationSeconds, reason) {
    return $Call.ByID(2287456290, durationSeconds, reason).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType4($result);
    }));
}

/**
 * @param {chi$0.Mux | null} r
 * @returns {$CancellablePromise<void>}
 */
export function RegisterHTTPHandlers(r) {
    return $Call.ByID(1862536413, r);
}

/**
 * RemoveWhitelist removes a whitelist entry by ID.
 * 
 * Parameters:
 *   - id: The ID of the whitelist entry to remove
 * 
 * Returns:
 *   - error: Database error if the deletion fails
 * @param {number} id
 * @returns {$CancellablePromise<void>}
 */
export function RemoveWhitelist(id) {
    return $Call.ByID(459092314, id);
}

/**
 * ResumeProtection re-enables focus protection and records the reason for resumption.
 * 
 * This function is called either automatically when a pause duration expires,
 * or manually by the user to end a pause early. The reason is persisted to the
 * database for auditing and analytics purposes.
 * 
 * Parameters:
 *   - reason: A human-readable explanation for why protection was resumed
 *     (e.g., "protection paused for 5m0s expired" or "user manually resumed")
 * 
 * Returns:
 *   - error: Returns an error if protection is not currently paused
 * 
 * Side effects:
 *   - Updates the ProtectionPause record in the database with ResumedAt timestamp
 *   - Clears the pause state and emits a state update via the state channel
 * @param {string} reason
 * @returns {$CancellablePromise<$models.ProtectionPause>}
 */
export function ResumeProtection(reason) {
    return $Call.ByID(2121344489, reason).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType4($result);
    }));
}

/**
 * TitleChanged is called when the title of the current application changes,
 * whether it's a new application or the same application title has changed
 * @param {string} executablePath
 * @param {string} windowTitle
 * @param {string} appName
 * @param {string} icon
 * @param {string | null} bundleID
 * @param {string | null} url
 * @returns {$CancellablePromise<void>}
 */
export function TitleChanged(executablePath, windowTitle, appName, icon, bundleID, url) {
    return $Call.ByID(908276631, executablePath, windowTitle, appName, icon, bundleID, url);
}

/**
 * Whitelist temporarily allows a specific blocked usage (by bundle ID and hostname) for the specified duration.
 * 
 * This function creates a ProtectionWhitelist entry that allows the specified application or website
 * to bypass focus protection for a limited time. This enables users to temporarily access blocked
 * content without pausing all protection. The whitelist entry is persisted to the database and can
 * be checked during termination decision evaluation.
 * 
 * Parameters:
 *   - bundleID: The application bundle identifier (e.g., "com.example.app")
 *   - hostname: The website hostname (e.g., "example.com") - empty string for non-browser apps
 *   - duration: The duration to allow the usage (defaults to 1 hour if 0)
 * 
 * Returns:
 *   - error: Database error if the whitelist entry creation fails
 * 
 * Side effects:
 *   - Creates a ProtectionWhitelist record in the database with expiration timestamp
 * @param {string} executablePath
 * @param {string} hostname
 * @param {time$0.Duration} duration
 * @returns {$CancellablePromise<void>}
 */
export function Whitelist(executablePath, hostname, duration) {
    return $Call.ByID(3397463026, executablePath, hostname, duration);
}

// Private type creation functions
const $$createType0 = $models.TerminationDecision.createFrom;
const $$createType1 = $models.ClassificationResponse.createFrom;
const $$createType2 = $Create.Nullable($$createType1);
const $$createType3 = $models.DayInsights.createFrom;
const $$createType4 = $models.ProtectionPause.createFrom;
const $$createType5 = $Create.Array($$createType4);
const $$createType6 = $models.SandboxExecutionLog.createFrom;
const $$createType7 = $Create.Array($$createType6);
const $$createType8 = $models.ApplicationUsage.createFrom;
const $$createType9 = $Create.Array($$createType8);
const $$createType10 = $models.ProtectionWhitelist.createFrom;
const $$createType11 = $Create.Array($$createType10);
