// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as apiv1$0 from "../../gen/api/v1/models.js";

/**
 * @returns {$CancellablePromise<string>}
 */
export function CheckoutLink() {
    return $Call.ByID(227579552);
}

/**
 * @returns {$CancellablePromise<apiv1$0.DeviceHandshakeResponse_AccountTier>}
 */
export function GetAccountTier() {
    return $Call.ByID(195842879);
}

/**
 * @returns {$CancellablePromise<string>}
 */
export function GetToken() {
    return $Call.ByID(2298031029);
}
