// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * Isolate is a JavaScript VM instance with its own heap and
 * garbage collector. Most applications will create one isolate
 * with many V8 contexts for execution.
 */
export class Isolate {
    /**
     * Creates a new Isolate instance.
     * @param {Partial<Isolate>} [$$source = {}] - The source object to create the Isolate.
     */
    constructor($$source = {}) {

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Isolate instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Isolate}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Isolate(/** @type {Partial<Isolate>} */($$parsedSource));
    }
}

/**
 * ObjectTemplate is used to create objects at runtime.
 * Properties added to an ObjectTemplate are added to each object created from the ObjectTemplate.
 */
export class ObjectTemplate {
    /**
     * Creates a new ObjectTemplate instance.
     * @param {Partial<ObjectTemplate>} [$$source = {}] - The source object to create the ObjectTemplate.
     */
    constructor($$source = {}) {

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ObjectTemplate instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ObjectTemplate}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ObjectTemplate(/** @type {Partial<ObjectTemplate>} */($$parsedSource));
    }
}
