// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * GetAll returns the latest version of each setting key.
 * 
 * Returns:
 *   - []Settings: A slice of settings with the latest version for each key
 *   - error: Database error if the query fails
 * @returns {$CancellablePromise<$models.Settings[]>}
 */
export function GetAll() {
    return $Call.ByID(2510514258).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * @param {$models.SettingsKey} key
 * @returns {$CancellablePromise<$models.Settings | null>}
 */
export function GetLatest(key) {
    return $Call.ByID(3784636452, key).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType2($result);
    }));
}

/**
 * GetVersionHistory returns the last N versions of a setting key, ordered by version descending.
 * 
 * Parameters:
 *   - key: The settings key to get history for
 *   - limit: Maximum number of versions to return
 * 
 * Returns:
 *   - []Settings: A slice of settings versions, newest first
 *   - error: Database error if the query fails
 * @param {$models.SettingsKey} key
 * @param {number} limit
 * @returns {$CancellablePromise<$models.Settings[]>}
 */
export function GetVersionHistory(key, limit) {
    return $Call.ByID(1011956779, key, limit).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * @param {$models.SettingsKey} key
 * @param {string} value
 * @returns {$CancellablePromise<void>}
 */
export function Save(key, value) {
    return $Call.ByID(1124565960, key, value);
}

// Private type creation functions
const $$createType0 = $models.Settings.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = $Create.Nullable($$createType0);
