/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ScreenTimeRouteImport } from './routes/screen-time'
import { Route as InsightsRouteImport } from './routes/insights'
import { Route as ActivityRouteImport } from './routes/activity'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ScreenTimeTrendsRouteImport } from './routes/screen-time/trends'
import { Route as ScreenTimeScreentimeRouteImport } from './routes/screen-time/screentime'
import { Route as InsightsTrendsRouteImport } from './routes/insights/trends'
import { Route as InsightsShareRouteImport } from './routes/insights/share'
import { Route as InsightsProjectsRouteImport } from './routes/insights/projects'
import { Route as InsightsDeepWorkRouteImport } from './routes/insights/deep-work'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ScreenTimeRoute = ScreenTimeRouteImport.update({
  id: '/screen-time',
  path: '/screen-time',
  getParentRoute: () => rootRouteImport,
} as any)
const InsightsRoute = InsightsRouteImport.update({
  id: '/insights',
  path: '/insights',
  getParentRoute: () => rootRouteImport,
} as any)
const ActivityRoute = ActivityRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ScreenTimeTrendsRoute = ScreenTimeTrendsRouteImport.update({
  id: '/trends',
  path: '/trends',
  getParentRoute: () => ScreenTimeRoute,
} as any)
const ScreenTimeScreentimeRoute = ScreenTimeScreentimeRouteImport.update({
  id: '/screentime',
  path: '/screentime',
  getParentRoute: () => ScreenTimeRoute,
} as any)
const InsightsTrendsRoute = InsightsTrendsRouteImport.update({
  id: '/trends',
  path: '/trends',
  getParentRoute: () => InsightsRoute,
} as any)
const InsightsShareRoute = InsightsShareRouteImport.update({
  id: '/share',
  path: '/share',
  getParentRoute: () => InsightsRoute,
} as any)
const InsightsProjectsRoute = InsightsProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => InsightsRoute,
} as any)
const InsightsDeepWorkRoute = InsightsDeepWorkRouteImport.update({
  id: '/deep-work',
  path: '/deep-work',
  getParentRoute: () => InsightsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/activity': typeof ActivityRoute
  '/insights': typeof InsightsRouteWithChildren
  '/screen-time': typeof ScreenTimeRouteWithChildren
  '/settings': typeof SettingsRoute
  '/insights/deep-work': typeof InsightsDeepWorkRoute
  '/insights/projects': typeof InsightsProjectsRoute
  '/insights/share': typeof InsightsShareRoute
  '/insights/trends': typeof InsightsTrendsRoute
  '/screen-time/screentime': typeof ScreenTimeScreentimeRoute
  '/screen-time/trends': typeof ScreenTimeTrendsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/activity': typeof ActivityRoute
  '/insights': typeof InsightsRouteWithChildren
  '/screen-time': typeof ScreenTimeRouteWithChildren
  '/settings': typeof SettingsRoute
  '/insights/deep-work': typeof InsightsDeepWorkRoute
  '/insights/projects': typeof InsightsProjectsRoute
  '/insights/share': typeof InsightsShareRoute
  '/insights/trends': typeof InsightsTrendsRoute
  '/screen-time/screentime': typeof ScreenTimeScreentimeRoute
  '/screen-time/trends': typeof ScreenTimeTrendsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/activity': typeof ActivityRoute
  '/insights': typeof InsightsRouteWithChildren
  '/screen-time': typeof ScreenTimeRouteWithChildren
  '/settings': typeof SettingsRoute
  '/insights/deep-work': typeof InsightsDeepWorkRoute
  '/insights/projects': typeof InsightsProjectsRoute
  '/insights/share': typeof InsightsShareRoute
  '/insights/trends': typeof InsightsTrendsRoute
  '/screen-time/screentime': typeof ScreenTimeScreentimeRoute
  '/screen-time/trends': typeof ScreenTimeTrendsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/activity'
    | '/insights'
    | '/screen-time'
    | '/settings'
    | '/insights/deep-work'
    | '/insights/projects'
    | '/insights/share'
    | '/insights/trends'
    | '/screen-time/screentime'
    | '/screen-time/trends'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/activity'
    | '/insights'
    | '/screen-time'
    | '/settings'
    | '/insights/deep-work'
    | '/insights/projects'
    | '/insights/share'
    | '/insights/trends'
    | '/screen-time/screentime'
    | '/screen-time/trends'
  id:
    | '__root__'
    | '/'
    | '/activity'
    | '/insights'
    | '/screen-time'
    | '/settings'
    | '/insights/deep-work'
    | '/insights/projects'
    | '/insights/share'
    | '/insights/trends'
    | '/screen-time/screentime'
    | '/screen-time/trends'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ActivityRoute: typeof ActivityRoute
  InsightsRoute: typeof InsightsRouteWithChildren
  ScreenTimeRoute: typeof ScreenTimeRouteWithChildren
  SettingsRoute: typeof SettingsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/screen-time': {
      id: '/screen-time'
      path: '/screen-time'
      fullPath: '/screen-time'
      preLoaderRoute: typeof ScreenTimeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/insights': {
      id: '/insights'
      path: '/insights'
      fullPath: '/insights'
      preLoaderRoute: typeof InsightsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/activity': {
      id: '/activity'
      path: '/activity'
      fullPath: '/activity'
      preLoaderRoute: typeof ActivityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/screen-time/trends': {
      id: '/screen-time/trends'
      path: '/trends'
      fullPath: '/screen-time/trends'
      preLoaderRoute: typeof ScreenTimeTrendsRouteImport
      parentRoute: typeof ScreenTimeRoute
    }
    '/screen-time/screentime': {
      id: '/screen-time/screentime'
      path: '/screentime'
      fullPath: '/screen-time/screentime'
      preLoaderRoute: typeof ScreenTimeScreentimeRouteImport
      parentRoute: typeof ScreenTimeRoute
    }
    '/insights/trends': {
      id: '/insights/trends'
      path: '/trends'
      fullPath: '/insights/trends'
      preLoaderRoute: typeof InsightsTrendsRouteImport
      parentRoute: typeof InsightsRoute
    }
    '/insights/share': {
      id: '/insights/share'
      path: '/share'
      fullPath: '/insights/share'
      preLoaderRoute: typeof InsightsShareRouteImport
      parentRoute: typeof InsightsRoute
    }
    '/insights/projects': {
      id: '/insights/projects'
      path: '/projects'
      fullPath: '/insights/projects'
      preLoaderRoute: typeof InsightsProjectsRouteImport
      parentRoute: typeof InsightsRoute
    }
    '/insights/deep-work': {
      id: '/insights/deep-work'
      path: '/deep-work'
      fullPath: '/insights/deep-work'
      preLoaderRoute: typeof InsightsDeepWorkRouteImport
      parentRoute: typeof InsightsRoute
    }
  }
}

interface InsightsRouteChildren {
  InsightsDeepWorkRoute: typeof InsightsDeepWorkRoute
  InsightsProjectsRoute: typeof InsightsProjectsRoute
  InsightsShareRoute: typeof InsightsShareRoute
  InsightsTrendsRoute: typeof InsightsTrendsRoute
}

const InsightsRouteChildren: InsightsRouteChildren = {
  InsightsDeepWorkRoute: InsightsDeepWorkRoute,
  InsightsProjectsRoute: InsightsProjectsRoute,
  InsightsShareRoute: InsightsShareRoute,
  InsightsTrendsRoute: InsightsTrendsRoute,
}

const InsightsRouteWithChildren = InsightsRoute._addFileChildren(
  InsightsRouteChildren,
)

interface ScreenTimeRouteChildren {
  ScreenTimeScreentimeRoute: typeof ScreenTimeScreentimeRoute
  ScreenTimeTrendsRoute: typeof ScreenTimeTrendsRoute
}

const ScreenTimeRouteChildren: ScreenTimeRouteChildren = {
  ScreenTimeScreentimeRoute: ScreenTimeScreentimeRoute,
  ScreenTimeTrendsRoute: ScreenTimeTrendsRoute,
}

const ScreenTimeRouteWithChildren = ScreenTimeRoute._addFileChildren(
  ScreenTimeRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ActivityRoute: ActivityRoute,
  InsightsRoute: InsightsRouteWithChildren,
  ScreenTimeRoute: ScreenTimeRouteWithChildren,
  SettingsRoute: SettingsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
